// @ts-ignore
import PDFDocument from 'pdfkit';
import { PayslipDetail } from './payslip.service';

export class PdfGeneratorService {
  static async generatePayslipPdf(payslip: PayslipDetail): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData);
        });

        // Header
        doc.fontSize(20).text('NexHR Official Payslip', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Payslip ID: #${payslip.id}`);
        doc.text(`Status: ${payslip.status}`);
        doc.text(`Employee: ${payslip.employee_name || payslip.employee_id}`);
        doc.text(`Department: ${payslip.department_name || 'General'}`);
        doc.text(`Period: ${payslip.period_start || ''} to ${payslip.period_end || ''}`);
        doc.moveDown();

        // Totals
        doc.fontSize(14).text('Summary', { underline: true });
        doc.fontSize(12).text(`Basic Wage: $${payslip.basic_wage.toFixed(2)}`);
        doc.text(`Gross Wage: $${payslip.gross_wage.toFixed(2)}`);
        doc.text(`Net Wage: $${payslip.net_wage.toFixed(2)}`);
        doc.moveDown();

        // Lines
        if (payslip.lines && payslip.lines.length > 0) {
          doc.fontSize(14).text('Earnings & Deductions', { underline: true });
          doc.moveDown();

          payslip.lines.forEach((line: any) => {
            const prefix = line.category === 'DEDUCTION' ? '-' : '+';
            doc.fontSize(12).text(`${line.name} (${line.code}): ${prefix}$${Number(line.amount).toFixed(2)}`);
          });
        }

        doc.moveDown(2);
        doc.fontSize(10).fillColor('grey').text('Generated by NexHR Enterprise Platform', { align: 'center' });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}

